### PR TITLE
Refactor CourseShowPage to include StudentForm

### LINKED ISSUE #17: Add Student Table to Course Show Page
Complete this after #56 and #55  

# User Story
* As an admin/instructor
* I can see a student roster on the course show page
* So that I know who is in my class

# Discussion

In issue #55 a Course Show Page was added to the app.

In issue #56 a course table was added that can display information from `/api/students/all`

Your job is simple: add an api call to the course show page to get the students for that course, and display in the table on the course show page.

# Acceptance Criteria

- [ ] On the course show page, there is a table with all of the students in it.

### LINKED ISSUE #41: Add student upload form to CourseShowPage
Part of #15

### PR DESCRIPTION
**Pull request by Division7**
### Merge after #42 and #39
In this PR, I am attempting to add the StudentForm from #42 to CourseShowPage, so that instructors can upload their course rosters to Organic. These changes are visible on: https://proj-organic-daniel-dev.dokku-12.cs.ucsb.edu/

Due to the last second nature, this also ends up being the PR that integrates StudentsTable into the form as well.
Extremely notable changes:
### Updated React-Testing-Library/user-events to 14.5 to alleviate file uploading problems, documented at https://github.com/testing-library/user-event/issues/632 and patched in 14.0 (https://github.com/testing-library/user-event/pull/794#issuecomment-979456344). Ran against the full test suite and did not appear to fail any test.

Documented reason why:
When using ``userEvent.upload(input, file)`` previous to version 14.0, if the form field was required on the form, it would not correctly set the path to the file and leave the javascript value field blank. As a result, when the form would be checked, it would not allow it to submit in testing, and as a result could not be tested on that version. After some research, an upgrade (and several hours off my life), I diagnosed it and allieviated it via this.

Closes #41 
Closes #17

### CODE REVIEW

**Comment by Division7** [comment]
Figured it out-- this version of userEvents breaks file uploads for react. See here: https://github.com/testing-library/user-event/issues/380

**Comment by Division7** [comment]
It appears there's a problem with the required tag, because if I remove it, it posts just fine. The file is correctly added to the upload box though, so I'm not sure where to go from here.

**Review by jason-rodrigues — DISMISSED** [review]
LGTM 😎

**Comment by Division7** [comment]
Note: this one has been ready to go, I was just preventing a future merge conflict with Tony's StudentsTable

**Review by jason-rodrigues — DISMISSED** [review]
LGTM! Merge conflicts were resolved, able to see stories and everything.

**Pull request merged**
