### PR TITLE
School Page UI Improvements

### LINKED ISSUE #28: UX improvements to SchoolForm.js (for creating/editing schools).
https://github.com/ucsb-cs156/proj-organic/issues/58

### PR DESCRIPTION
**Pull request by SR33G33**
Closes #28 
Improvements for the School Edit Pages UI

Update:
Removed termError (sending empty string to backend for now):
image
Doesn't affect functionality:
image

Tooltips:
image
image
image

Deployed on our [QA deployment](https://organic-qa.dokku-12.cs.ucsb.edu/) as both Sreeganesh's and my dev deployments are being used for our respective PRs.

### CODE REVIEW

**Comment by jason-rodrigues** [comment]
Update:
Removed termError (sending empty string to backend for now):
image
Doesn't affect functionality:
image


Tooltips:
image
image
image

Deployed on our [QA deployment](https://organic-qa.dokku-12.cs.ucsb.edu/) as both Sreeganesh's and my dev deployments are being used for our respective PRs.

**Review by Division7 — DISMISSED** [review]
LGTM!

**Review by pconrad — APPROVED** [review]
LGTM

**Review by Simonmann17 — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
