### PR TITLE
Upgrading Backend to Spring-Boot 3.2.5

### LINKED ISSUE #9: Update Backend to Spring 3
In this issue, we'll update the backend code to Spring 3

# Why we need to do this.

* Security; some of the dependencies we are using have security issues that are only patched in Spring 3.  (This is the main reason)
* Features; Spring 3 has some capabilities that are not present in Spring 2. (At moment, none of them are critical, but it would be better to be on the version of Spring that is getting more updates.)

# How to do it

This PR shows how we updated the code base for STARTER-team03 to Spring 3.  It is likely that if you do the exact same things, it will work for this code base:

* <https://github.com/ucsb-cs156-f24/STARTER-team03/pull/13>

# Notes

* Q: Do I need the aop class that is in the STARTER-team03 code?
  * A: No, it's not necessary. However, that's also a nice thing to add, and we'll make a separate issue for that.
* Q: The STARTER-team03 has code for integration and end2end tests.  Do we need to add those in this issue?
  * A: No.  However, adding the lines in the pom.xml that exclude those from pitest is still a good idea, since those might get added into the code base in the future.

### PR DESCRIPTION
**Pull request by Division7**
In this PR, I upgraded the backend to Spring Boot 3.2.1. I used the team03 starter [as a reference](https://github.com/ucsb-cs156-f24/STARTER-team03/pull/13), and retooled the SecurityConfig class to match. I then hammered out the import statement changes with some help from Intellij IDEA, before ensuring that the tests passed by making necessary changes there. I mostly did my best to follow the model, but I did try to sort out some the import statement jumble by ignoring changes that appeared to move import statements around.

To end the final missing line coverage, I tested the ensuing test and realized there were no Mockito markers in the mapping. As a result, I removed the offending code from the project without having to modify the tests, as it was unused.

I had 100% code coverage and 100% mutations killed locally.
Changes are visible at [https://proj-organic-daniel-dev.dokku-12.cs.ucsb.edu/](https://proj-organic-daniel-dev.dokku-12.cs.ucsb.edu/)

Closes #9

### CODE REVIEW

**Comment by pconrad** [comment]
Hi @Division7 ... I suggest putting this one on the backburner while the staff figures out some issues with Spring Boot 3's handling of CSRF tokens, and a few other things.  

The work you've done so far is great, and once we resolve a few things, we'll have a new PR for you to compare against. For now, I suggest setting this aside, and picking something else from the TODO list to work on.

**Review by SR33G33 — APPROVED** [review]
LGTM!!!!! 😎

**Review by pconrad — APPROVED** [review]
LGTM!

**Comment by pconrad** [comment]
Note: This team earned 20 points rather than 10 because @Division7 was the developer that figured out the reason folks were having trouble deploying on dokku, specifically an issue with how Spring 3 handles SQL dialect detection differently than Spring 2, requiring an adjustment in the properties files.

**Pull request merged**
